name: qr_scanner
description: A Flutter QR Code and Barcode Scanner/Generator with AdMob Integration
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.7+8

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  qr_flutter: ^4.1.0
  path_provider: ^2.1.3
  share_plus: ^11.0.0
  google_mobile_ads: ^6.0.0
  url_launcher: ^6.3.1
  syncfusion_flutter_barcodes: ^30.1.40
  package_info_plus: ^8.3.0
  add_2_calendar: ^3.0.1
  flutter_contacts: ^1.1.9+2
  permission_handler: ^12.0.1
  intl: ^0.20.2
  wifi_iot: ^0.3.19+2
  mobile_scanner: ^7.0.1
  image_picker: ^1.1.2
  google_mlkit_barcode_scanning: ^0.14.1

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    - assets/icon/icon.png
